Repository AI-Jiwoo/Jiwoo-AI-Server, pull requests merged in 2024-08, with the labels that each got.

#1 [Feature] Chat-bot 기능 구현
  README.md
  app/api/routes.py
  app/chatbot.py
  app/database.py
  app/embeddings.py
  app/models.py
  app/vector_store.py
  create_collection.py
  data/business_info.txt
  data/side_projects.txt
  data/startup_guide.txt
  main.py
  requirements.txt
Labels: enhancement

#2 [Fix] Chat-bot 기존 대화 불러올 수 있도록 설정 변경
  README.md
  app/chatbot.py
Labels: bug, enhancement

#3 [Refactor] 전체 코드 리팩토링
  app/api/routes.py
  config/settings.py
  create_collection.py
  data/business_info.txt
  data/side_projects.txt
  data/startup_guide.txt
  main.py
  services/chatbot.py
  services/models.py
  utils/database.py
  utils/embedding_utils.py
  utils/vector_store.py
Labels: enhancement

#4 [Feature] AI Chat-Bot Web 검색기능 구현
  config/settings.py
  main.py
  requirements.txt
  services/chatbot.py
  utils/database.py
  utils/vector_store.py
  utils/web_search.py
Labels: enhancement

#5 [CICD] EC2에 Python Server 배포 WorkFlow 구현
  .github/workflows/deploy.yml
  .gitignore
Labels: enhancement

#6 [Release] EC2 통합 배포 환경 세팅(실제 배포 적용)
  .github/workflows/deploy.yml
  .gitignore
Labels: enhancement

#7 [CICD] HOST 수정
  .github/workflows/deploy.yml
  config/settings.py
Labels: bug, enhancement

#8 [Release] HOST 수정 후 재배포
  .github/workflows/deploy.yml
  config/settings.py
Labels: bug, enhancement

#9 [Feature] 지원 사업에 해당하는 사업 검색 기능 구현
  .pre-commit-config.yaml
  README.md
  app/__init__.py
  app/api/routes.py
  config/settings.py
  main.py
  pyproject.toml
  requirements.txt
  services/chatbot.py
  services/models.py
  utils/database.py
  utils/embedding_utils.py
  utils/vector_store.py
  utils/web_search.py
Labels: enhancement

#10 [Release] 지원 사업에 해당하는 사업 검색 기능 반영
  .pre-commit-config.yaml
  README.md
  app/__init__.py
  app/api/routes.py
  config/settings.py
  main.py
  pyproject.toml
  requirements.txt
  services/chatbot.py
  services/models.py
  utils/database.py
  utils/embedding_utils.py
  utils/vector_store.py
  utils/web_search.py
Labels: release

#11 [Fix] route.py logging 처리 및 content 파싱 추가
  app/api/routes.py
Labels: bug

#12 [Fix] route.py logging 처리 및 content 파싱 추가 반영
  app/api/routes.py
Labels: bug, release

#13 [Performance] 검색 API 수정 및 의도분석, 검색쿼리 생성 기능 구현
  .github/workflows/deploy.yml
  app/api/routes.py
  config/settings.py
  docker-compose.yml
  requirements.txt
  services/chatbot.py
  services/models.py
  utils/intent_analyzer.py
  utils/query_generator.py
  utils/vector_store.py
  utils/web_search.py
Labels: bug, enhancement

#14 [Release] 검색 API 교체 및 검색 성능 향상
  .github/workflows/deploy.yml
  app/api/routes.py
  config/settings.py
  docker-compose.yml
  requirements.txt
  services/chatbot.py
  services/models.py
  utils/intent_analyzer.py
  utils/query_generator.py
  utils/vector_store.py
  utils/web_search.py
Labels: enhancement, release

#15 [CI] 배포 시 환경 생성 코드 추가
  .github/workflows/deploy.yml
Labels: bug, release

#16 [Performance] Web 검색 기능 고도화
  app/api/routes.py
  config/settings.py
  drop_collection.py
  requirements.txt
  services/chatbot.py
  services/models.py
  utils/database.py
  utils/embedding_utils.py
  utils/graph_generator.py
  utils/query_generator.py
  utils/vector_store.py
  utils/web_search.py
Labels: enhancement

#17 [Build] 누락된 라이브러리 추가
  requirements.txt
Labels: bug

#18 [Fix] 요청 토큰 수로 인한 대화기록 수정
  services/chatbot.py
Labels: bug

#19 [Performance] Chatbot 대화시 토큰 제한 개선 및 그래프 기능 개선
  config/settings.py
  services/chatbot.py
  utils/graph_generator.py
Labels: bug, enhancement, release

#21 [Performance] 가드레일 설정 및 구조 개선
  app/api/routes.py
  config/settings.py
  drop_collection.py
  services/chatbot.py
  services/models.py
  utils/database.py
  utils/embedding_utils.py
  utils/graph_generator.py
  utils/intent_analyzer.py
  utils/query_generator.py
  utils/vector_store.py
  utils/web_search.py
Labels: release

#22 [Performance] 페르소나 부여 및 프롬프팅 수정
  services/chatbot.py
  utils/graph_generator.py
Labels: enhancement

#20 [Performance] 세무정보 vectorDB 저장 및 챗봇 연결
  app/api/routes.py
  config/settings.py
  requirements.txt
  services/chatbot.py
  services/models.py
  services/taxationChatBot.py
  utils/database.py
  utils/embedding_utils.py
  utils/fileSave.py
  utils/graph_generator.py
  utils/intent_analyzer.py
  utils/query_generator.py
  utils/save_IncomRates.py
  utils/save_VATInfo.py
  utils/save_simpleTransaction.py
  utils/save_tax_calcution_flow.py
  utils/save_tax_info.py
  utils/save_tax_method_url.py
  utils/taxation.py
  utils/vector_store.py
  utils/web_search.py
Labels: enhancement

#23 [Fix] host 이름 변경
  config/settings.py
Labels: bug

#24 [Fix] 사업정보 삽입 데이터 수정
  app/api/routes.py
Labels: bug

#25 [Fix]vector store 설정 수정
  utils/vector_store.py
Labels: bug

#26 [Fix] vector store 수정
  utils/vector_store.py
Labels: bug
